name: 'TW SaaS Fargate Deployment'
description: 'Deploy a new version of a service to ECS Fargate'
inputs:
  service:
    description: 'The name of the service to be updated, e.g. "agenda"'
    required: true
    default: 'World'
  version:
    description: 'Version of the updated service, e.g. 1.0.2'
    required: true
  department:
    description: 'Specify which department is responsible for the service, e.g. "saas"'
    required: true
  taskCount:
    description: 'How many tasks should run in parallel as part of the service'
    required: true
    default: '1'
  environment:
    description: 'The referenced environment for the deployment'
    required: true
  withLocal:
    description: 'Defines whether a local image should also be tagged in the dev environment'
    required: false
    default: 'true'
  taskDefinitionPath:
    description: 'Defines where the task definition is located'
    required: true
    default: 'taskdefinition.js'
  shouldBuildImage:
    description: 'Defines if the docker image should be build or already exists'
    required: false
    default: false
  ecrRegistry:
    description: 'Defines the ECR registry'
    required: true
    
runs:
  using: 'node12'
  main: 'dist/index.js'
